sudo: false
language: android
jdk: oraclejdk8
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
android:
  components:
      - tools
      - build-tools-28.0.3
      - android-28
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-android-support
      - sys-img-armeabi-v7a-android-22 # <---- This should add the system image

before_script:
  - android list targets # list pre-installed targets # <---- list all installed targets
  - android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # <---- list all available components
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a # <---- this is failing, "Target id is not valid"
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
install:
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - ./vendor/bundle
before_script:
  - android list targets # list pre-installed targets # <---- list all installed targets
  - android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # <---- list all available components
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a # <---- this is failing, "Target id is not valid"
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - bundle exec ruby ./build-script/build-android.rb

branches:
        only:
                - master