/*
 * WAZIUP API
 * This API allows you to access all Waziup services. In order to access protected services,
 * first get a token with POST /auth/token. Then insert this token in the authorization key,
 * specifying \"Bearer\" in front. For example \"Bearer: eyJhbGc...\".
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.waziup.waziup_da_app.data.network.model.user;

import com.google.gson.annotations.SerializedName;

/**
 * User
 */

public class User {

    @SerializedName("id")
    public String id = null;

    @SerializedName("username")
    public String username = null;

    @SerializedName("firstName")
    public String firstName = null;

    @SerializedName("lastName")
    public String lastName = null;

    @SerializedName("email")
    public String email = null;

    @SerializedName("phone")
    public String phone = null;

    @SerializedName("address")
    public String address = null;

    @SerializedName("facebook")
    public String facebook = null;

    @SerializedName("twitter")
    public String twitter = null;

}

